package tw.junba.ktvmultitrack

import android.content.ContentResolver
import android.net.Uri
import android.provider.OpenableColumns
import org.json.JSONArray
import org.json.JSONObject
import java.net.HttpURLConnection
import java.net.URL

object GeminiApi {
    private fun postJson(url:String, body:String):String{val c=URL(url).openConnection() as HttpURLConnection;c.requestMethod="POST";c.doOutput=true;c.connectTimeout=30000;c.readTimeout=180000;c.setRequestProperty("Content-Type","application/json; charset=utf-8");c.outputStream.use{it.write(body.toByteArray())};val code=c.responseCode;val txt=(if(code in 200..299)c.inputStream else c.errorStream).bufferedReader().readText();if(code !in 200..299)throw RuntimeException("HTTP $code: $txt");return txt}
    private fun responseText(json:String):String{val o=JSONObject(json);val parts=o.getJSONArray("candidates").getJSONObject(0).getJSONObject("content").getJSONArray("parts");return parts.getJSONObject(0).optString("text","")}
    private fun jsonArrayFromText(s:String):JSONArray{var x=s.trim().replace(Regex("^```(?:json)?\\s*",RegexOption.IGNORE_CASE),"").replace(Regex("\\s*```$"),"");val a=x.indexOf('[');val b=x.lastIndexOf(']');if(a>=0&&b>a)x=x.substring(a,b+1);return JSONArray(x)}
    fun polish(track:TextTrack,key:String,model:String):TextTrack{
        val out= mutableListOf<Segment>(); val batch=24
        for(off in track.segments.indices step batch){val p=track.segments.subList(off,minOf(off+batch,track.segments.size));val arr=JSONArray();p.forEachIndexed{i,s->arr.put(JSONObject().put("id",i).put("speaker",s.speaker).put("text",s.text))};val prompt="你是繁體中文會議逐字稿校稿助理。只回傳 JSON 陣列 [{\\\"id\\\":0,\\\"text\\\":\\\"...\\\"}]。使用台灣繁體中文，修正錯字與贅詞但不得新增事實，保留每個 id。輸入：$arr";val req=JSONObject().put("contents",JSONArray().put(JSONObject().put("parts",JSONArray().put(JSONObject().put("text",prompt)))));val r=postJson("https://generativelanguage.googleapis.com/v1beta/models/$model:generateContent?key=$key",req.toString());val got=jsonArrayFromText(responseText(r));val map=mutableMapOf<Int,String>();for(i in 0 until got.length()){val o=got.optJSONObject(i)?:continue;map[o.optInt("id",-1)]=o.optString("text","")};p.forEachIndexed{i,s->out+=s.copy(text=map[i]?.ifBlank{s.text}?:s.text)}}
        return TextTrack(track.name+"｜Gemini順稿",out,"Gemini",track.timed,track.estimated)
    }
    private fun size(cr:ContentResolver,u:Uri):Long{cr.query(u,arrayOf(OpenableColumns.SIZE),null,null,null)?.use{c->if(c.moveToFirst())return c.getLong(0)};return -1}
    private fun mime(cr:ContentResolver,u:Uri)=cr.getType(u) ?: "audio/mpeg"
    private fun upload(cr:ContentResolver,u:Uri,key:String):Pair<String,String>{val len=size(cr,u);if(len<=0)throw RuntimeException("無法取得音檔大小");val mt=mime(cr,u);val start=URL("https://generativelanguage.googleapis.com/upload/v1beta/files?key=$key").openConnection() as HttpURLConnection;start.requestMethod="POST";start.doOutput=true;start.setRequestProperty("X-Goog-Upload-Protocol","resumable");start.setRequestProperty("X-Goog-Upload-Command","start");start.setRequestProperty("X-Goog-Upload-Header-Content-Length",len.toString());start.setRequestProperty("X-Goog-Upload-Header-Content-Type",mt);start.setRequestProperty("Content-Type","application/json");start.outputStream.use{it.write("{\"file\":{\"display_name\":\"junba_review_audio\"}}".toByteArray())};if(start.responseCode !in 200..299)throw RuntimeException(start.errorStream.bufferedReader().readText());val uploadUrl=start.getHeaderField("X-Goog-Upload-URL")?:throw RuntimeException("Gemini 未回傳上傳網址");val up=URL(uploadUrl).openConnection() as HttpURLConnection;up.requestMethod="POST";up.doOutput=true;up.fixedLengthStreamingMode(len);up.setRequestProperty("Content-Type",mt);up.setRequestProperty("X-Goog-Upload-Offset","0");up.setRequestProperty("X-Goog-Upload-Command","upload, finalize");cr.openInputStream(u)!!.use{input->up.outputStream.use{out->input.copyTo(out)}};val txt=(if(up.responseCode in 200..299)up.inputStream else up.errorStream).bufferedReader().readText();if(up.responseCode !in 200..299)throw RuntimeException(txt);val file=JSONObject(txt).optJSONObject("file")?:JSONObject(txt);return Pair(file.getString("uri"),file.optString("mimeType",mt))}
    fun transcribeForReview(cr:ContentResolver,u:Uri,key:String,model:String):TextTrack{val (uri,mt)=upload(cr,u,key);val prompt="請完整聽錄音並建立核對逐字稿。辨識不同講者為講者1、講者2等，不猜姓名。每段輸出 start 秒數、end 秒數、speaker、text。中文使用繁體中文台灣用語。只輸出 JSON 陣列，不要 markdown。";val parts=JSONArray().put(JSONObject().put("file_data",JSONObject().put("mime_type",mt).put("file_uri",uri))).put(JSONObject().put("text",prompt));val req=JSONObject().put("contents",JSONArray().put(JSONObject().put("parts",parts)));val r=postJson("https://generativelanguage.googleapis.com/v1beta/models/$model:generateContent?key=$key",req.toString());val arr=jsonArrayFromText(responseText(r));val segs=mutableListOf<Segment>();for(i in 0 until arr.length()){val o=arr.optJSONObject(i)?:continue;val tx=o.optString("text","");if(tx.isNotBlank())segs+=Segment(o.optDouble("start",0.0),o.optDouble("end",o.optDouble("start",0.0)),tx,o.optString("speaker",""))};return TextTrack("Gemini智慧核對",segs,"Gemini Audio",true,false)}
}
